config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'application#home'

  get 'admin', to: 'admin/banks#index'
  namespace :admin do
    resources :banks
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  validates_presence_of :name

  self.per_page = 5
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_admin!

  layout 'admin'
end

app/controllers/admin/banks_controller.rb
class Admin::BanksController < Admin::AdminController

  def index
    @banks = Bank.all.paginate(page: page_param)
  end

  def new
    @banks = Bank.all
    @bank = Bank.new
  end

  def create
    @bank = Bank.new(bank_params)

    if @bank.save
      flash[:notice] = 'Bank has been created successfully.'
      redirect_to admin_banks_url
    else
      render :new
    end
  end

  def edit
    @bank = Bank.find(bank_id)
    @banks = Bank.all
  end

  def update
    @bank = Bank.find(bank_id)
    if @bank.update(bank_params)
      flash[:notice] = 'Bank has been updated successfully.'
      redirect_to admin_banks_url
    else
      flash[:alert] = 'Failed to update bank.'
      render :edit
    end
  end

  def destroy
    @bank = Bank.find(bank_id)
    @bank.destroy
    flash[:notice] = "Bank has been deleted successfully."
    redirect_to admin_banks_path
  end

  protected
  def bank_id
    params.require(:id)
  end
  def bank_params
    params.require(:bank).permit(:name)
  end
  def page_param
    params.fetch(:page, 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/banks/edit.html.slim
h3 Edit Bank ##{@bank.id}
.row
  .col-md-6
    = simple_form_for [:admin, @bank] do |form|
      = form.input :name
      = form.submit 'Edit', class: 'btn btn-success'

app/views/admin/banks/index.html.slim
h2 List of Banks
.row
  .col-md-12
    = link_to 'Create Bank', new_admin_bank_path, class: 'btn btn-info'
.row
  .col-md-12
    table.table
      thead
        tr
          th Name
          th Edit
          th Delete
      tbody
        - @banks.each do |bank|
          tr
            td
              = bank.name
            td
              = link_to 'Edit', edit_admin_bank_path(bank),
                                data: {test: "bank-edit-#{bank.id}"},
                                class: 'btn btn-warning btn-sm'
            td
              = button_to 'Delete', admin_bank_path(bank),
                                    method: :delete,
                                    data: {test: "bank-delete-#{bank.id}"},
                                    class: 'btn btn-danger btn-sm'

      tfoot
        tr
          td colspan=3
            = will_paginate @banks, renderer: BootstrapPagination::Rails

app/views/admin/banks/new.html.slim
h3 Add new bank

.row
  .col-md-6
    = simple_form_for [:admin, @bank] do |form|
      = form.input :name
      = form.submit 'Create', class: 'btn btn-success'

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | Tindung
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #header
      nav.navbar.navbar-default
        .container
          .navbar-header
            = link_to 'Tindung Admin', admin_path, class: 'navbar-brand'

          ul.nav.navbar-nav.navbar-right.col-md-4
            - if admin_signed_in?
              li= link_to "Welcome, #{current_admin.email}!", '#'
              li= link_to 'Sign out', destroy_admin_session_path, method: :delete
            - else
              li= link_to 'Sign in', new_admin_session_path

    #main-body.container
      .row
        .col-md-3
          - if admin_signed_in?
            = render_navigation :expand_all => true, :renderer => :bootstrap
        .col-md-9
          = flash_messages
          = yield
    #footer.container

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tindung
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    section.container
      .col-md-12
        = flash_messages
        = yield